language: android
jdk:
    - oraclejdk8
android:
  components:
    # The BuildTools version used by this app
    - tools
    - build-tools-28.0.3

    # The SDK version used to compile Argentum
    - android-28

before_install: 
  - yes | sdkmanager "platforms;android-28"
script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug testDebugUnitTest

licenses:
  - '.+'
